name: arkid-fe v2 wjw build image 2

on:
  push:
    branches:
      - feature-notice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          harbor.longguikeji.com/arkid-hpwjw/arkid-fe-feature-notice:latest
          harbor.longguikeji.com/arkid-hpwjw/arkid-fe-feature-notice:v2dev-${{ github.run_number }}
